### ISSUE TITLE
Wmii seems to be deprecated

### ISSUE THREAD

**Issue by julianferres** [sminez/qtile-config#1]
After running your configuration in my computer, I have the error of qtile.layout not having attribute Wmii. Seems that `libqtile.layout.wmii.Wmii` has been deprecated by `libqtile.layout.columns.Columns`. It is mentioned in the page 53 of [Qtile Documentation](https://docs.qtile.org/_/downloads/en/v0.13.0/pdf/)

**Comment by sminez** [comment]
The last commit for this repo was two years ago. I wouldn't expect it to work out of the box anymore...
